#!/bin/bash
#

export USER=jmurray
device=toro
bdev=cm_$device-userdebug
cm=/home/$USER/android/cm
out=$cm/out/target/product/$device

echo ""
echo "Selected Device: $device"

cd $cm


echo ""
echo "Current branch info:"
echo ""

repo branches | grep "*"


echo ""
echo "Running repo sync..."
echo ""

repo sync -j32


echo ""
echo "Setting up for build"
echo ""

source build/envsetup.sh && lunch $bdev


echo ""
echo "Running make on `grep 'processor' /proc/cpuinfo | wc -l` processors"
echo ""

make -j`grep 'processor' /proc/cpuinfo | wc -l` otapackage


#echo ""
#echo "Build finished, copying zip to desktop" 
#echo ""

zname=`ls $out | grep ota`

cp $out/$zname ../mine/builds/cm_$device-ota-eng.$USER.$(date +%Y%m%d-%H%M).zip
cd ../mine/builds
md5sum cm_$device-ota-eng.$USER.$(date +%Y%m%d-%H%M).zip > cm_$device-ota-eng.$USER.$(date +%Y%m%d).zip.md5

echo ""
echo "Done!"
